### ISSUE TITLE
Cannot install with Pypi

### ISSUE THREAD

**Issue by VictorAtPL** [DevBruce/cmask2polygons#1]
Hi,
thank you for your work!

When I want to install your pkg via `pip install`, I get following error:

```
Collecting cmask2polygons==1.1.1
				
Could not find a version that satisfies the requirement cmask2polygons==1.1.1 (from versions: )
No matching distribution found for cmask2polygons==1.1.1
```

Presumably it's because I am using Python v. 3.6.9. Why do you require >=3.7.5? Can you loosen the requirements?

**Comment by devbruce** [comment]
Thanks for your feedback.
According to your request, I have changed the `python_requires>=3.7.5` to `python_requires>=3.6.5`.
If you have any other problems, Feel free to ask.
